### ISSUE TITLE
Pre-render Not Supported message

### ISSUE THREAD

**Issue by hassanbazzi** [preactjs/wmr#236] opened 2020-12-06 12:19 UTC
When I try to pre-render, I get the following error:

```
Error: Not supported
    at eval (eval at MJe ([worker eval]:1:710), <anonymous>:3:1)
    at MJe ([worker eval]:1:756)
```

You can see my full source on https://github.com/hassanbazzi/portfolio-wmr

I tried deleting my entire code and only keeping my index.html and index.js with just an empty `app` div, same error. 

Edit: I tried starting a project from scratch with `npm init wmr ...`, and I got the same error.

SOLVED: The problem was that I was on version 12 of Node. Moving to 14 fixed it. Maybe we should mention this somewhere.

**Comment by developit** [comment] 2020-12-06 20:08
Node 12 should be supported, even for Prerendering - any idea which version of 12.x?

It's possible for 12.7 and prior we need to [manually enable modules](https://github.com/preactjs/wmr/blob/a1328a94c3f9dba9b84e1ce90aef3adab2229755/src/lib/prerender.js#L18) in the worker.

**Comment by Snugug** [comment] 2020-12-23 13:04
Did #237  close this issue? If so, this looks to be the last issue in the 1.1 milestone and it'd be great to get a new version published. Thank you!

**Comment by dstaley** [comment] 2020-12-24 23:41
Just wanna share that I'm running into this issue on node 12.15 on Windows.

```
PS C:\Users\Dylan\Desktop\wmr-app> npm run build

> @ build C:\Users\Dylan\Desktop\wmr-app
> wmr build --prerender

Wrote 22Kb to disk:
  index.html 480b  
  index.8ca71c5f.js 16Kb
  chunks/index.d505420a.js 225b
  chunks/prerender.cacfed1e.js 4.9Kb
  assets/style.e6ee4bcf.css 499b
Error: Not supported
    at eval (eval at MJe ([worker eval]:1:710), <anonymous>:3:1)
    at MJe ([worker eval]:1:756)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `wmr build --prerender`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dylan\AppData\Roaming\npm-cache\_logs\2020-12-24T08_24_59_014Z-debug.log
PS C:\Users\Dylan\Desktop\wmr-app> node -v
v12.15.0
```

**Comment by developit** [comment] 2021-01-03 03:30
Hi @dstaley - WMR 1.1.0 was just published and it should provide a better error here. Your Node version should technically support workers though, perhaps the problem is actually something else?

**Comment by dstaley** [comment] 2021-01-03 03:54
Hmm, after updating to v1.10, I still get the same error:

```
PS C:\Users\Dylan\Desktop> npm init wmr test-wmr
npx: installed 1 in 1s
√ installed WMR.
√ project created!

To get started:
$ cd test-wmr

Start the development server:
$ npm start

Create a production build:
$ npm run build

Serve the app in production mode:
$ PORT=8080 npm run serve


To enable ESLint: (optional)
$ npm i eslint eslint-config-preact

PS C:\Users\Dylan\Desktop> cd .\test-wmr\

PS C:\Users\Dylan\Desktop\test-wmr> npm run build

> @ build C:\Users\Dylan\Desktop\test-wmr
> wmr build --prerender

Wrote 22Kb to disk:
  index.html 469b
  index.dbbadbd2.js 16Kb
  chunks/index.56ab0932.js 214b
  chunks/prerender.9cac9f0c.js 4.9Kb
  assets/style.e6ee4bcf.css 499b
Error: Not supported
    at eval (eval at BJe ([worker eval]:1:741), <anonymous>:3:1)
    at BJe ([worker eval]:1:787)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `wmr build --prerender`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dylan\AppData\Roaming\npm-cache\_logs\2021-01-03T03_51_48_095Z-debug.log

PS C:\Users\Dylan\Desktop\test-wmr> npm ls wmr
C:\Users\Dylan\Desktop\test-wmr
`-- wmr@1.1.0
```

**Comment by KoharaKazuya** [comment] 2021-01-26 09:27
I encountered this error too.
The error ocurrs in Node v12.16.3, but doesn't occur in Node v12.17.0. (I switched Node versions by nodebrew)

Reproduction steps:

```console
$ npm init wmr my-demo
$ cd $_
$ npm run build
```

**Comment by joaoantunesTD** [comment] 2021-04-22 07:46
The same to me! I was having the error with `v12.16.3`. Changed my version using volta and have no error anymore. My current node version is `v14.16.1`

**Closed** 2021-04-25 05:31 UTC
Labels: bug, discussion, documentation, needs more info
