### ISSUE TITLE
create-wmr: Cannot find module 'string_decoder/'

### ISSUE THREAD

**Issue by aduh95** [preactjs/wmr#371] opened 2021-02-23 14:20 UTC
I'm unable to create a wmr project (using Node.js v15.8.0, macOS):
```console
$ yarn create wmr viz.js-playground
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-wmr@0.1.4" with binaries:
      - create-wmr
[####] 4/4node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'string_decoder/'
Require stack:
- …/.config/yarn/global/node_modules/create-wmr/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (…/.config/yarn/global/node_modules/create-wmr/dist/index.js:2:194)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '…/.config/yarn/global/node_modules/create-wmr/dist/index.js'
  ]
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-wmr
Arguments: viz.js-playground
Directory: …
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
$ npm init wmr your-project-name
Need to install the following packages:
  create-wmr
Ok to proceed? (y) 
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'string_decoder/'
Require stack:
- …/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (…/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js:2:194)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '…/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js'
  ]
}
npm ERR! code 1
npm ERR! path …
npm ERR! command failed
npm ERR! command sh -c create-wmr your-project-name

npm ERR! A complete log of this run can be found in:
npm ERR!     …/.npm/_logs/2021-02-23T14_16_42_709Z-debug.log
```

Maybe an issue with 0.1.4 release?

**Comment by developit** [comment] 2021-02-23 22:49
Hiya! The 0.1.4 release was broken, but we've just published [0.2.0](https://github.com/preactjs/wmr/releases/tag/create-wmr%400.2.0) that works.

**Comment by wiesson** [comment] 2021-05-12 07:47
I think it's still broken 🤔 

```
$ Dev node --version        
v16.1.0
$ Dev npm init wmr hello-wmr 
Need to install the following packages:
  create-wmr
Ok to proceed? (y) y
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'string_decoder/'
Require stack:
- /Users/wiese/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/wiese/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js:2:194)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wiese/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js'
  ]
}
npm ERR! code 1
npm ERR! path /Users/wiese/Dev
npm ERR! command failed
npm ERR! command sh -c create-wmr "hello-wmr"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wiese/.npm/_logs/2021-05-12T07_46_40_624Z-debug.log
```

**Comment by marvinhagemeister** [comment] 2021-06-13 21:07
Closing, can't reproduce that anymore on any of my machines 🎉

**Closed by marvinhagemeister** 2021-06-13 21:07 UTC
Labels: infra
